CREATE TABLE bot_sessions (
    session_id          TEXT PRIMARY KEY,
    sf_bot_session_id   TEXT,
    case_id             TEXT,
    traffic_variant     TEXT NOT NULL DEFAULT 'bot_v1',
    handling_state      TEXT NOT NULL DEFAULT 'BOT_HANDLING',
    current_phase       TEXT NOT NULL DEFAULT 'INIT',
    active_use_case     TEXT,
    candidate_use_cases TEXT[],
    intent_confidence   NUMERIC(4,2),
    total_bot_turns     INT NOT NULL DEFAULT 0,
    clarification_count INT NOT NULL DEFAULT 0,
    faq_miss_count      INT NOT NULL DEFAULT 0,
    repeated_action_count INT NOT NULL DEFAULT 0,
    last_action         TEXT,
    form_topic_subject  TEXT,
    form_context        JSONB,
    customer_context    JSONB,
    listing_context     JSONB,
    moderation_context  JSONB,
    articles_shown      TEXT[] NOT NULL DEFAULT '{}',
    intake_fields       JSONB,
    containment_outcome TEXT,
    escalation_reason   TEXT,
    prompt_version      TEXT NOT NULL DEFAULT 'v1.0.0',
    model_version       TEXT NOT NULL DEFAULT 'local',
    projection_version  TEXT NOT NULL DEFAULT 'v1.0.0',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    closed_at           TIMESTAMPTZ
);
CREATE INDEX idx_sessions_handling ON bot_sessions(handling_state) WHERE handling_state != 'CLOSED';
